name: github-actions

on:
  push:
    branches: [ main ]
  pull-request: 
    branches: [ main ]
  workflow_dispatch:

jobs:
  style: 
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4.2.2

      - name: Set up Python environment
        uses: actions/setup-python@v5.4.0
        with:
          python-version: "3.10"
      - name: flake8 Lint
        uses: py-actions/flake8@v2