name: Flake 8 Lint and Pytest

on:
  push:
    branches: [ main ]
  pull_request: 
    branches: [ main ]
  workflow_dispatch:

jobs:
  flake8-lint: 
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4.2.2

      - name: Set up Python environment
        uses: actions/setup-python@v5.4.0
        with:
          python-version: "3.10"
      - name: flake8 Lint
        uses: py-actions/flake8@v2
        with:
          ignore: "E501"

  tests:
    needs: flake8-lint # Depends on previous job
    # The type of runner that the job will run on
    runs-on: ubuntu-latest 
    timeout-minutes: 10

    name: Pytest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest
        if [ -f Calculadora_Team3/requirements.txt ]; then pip install -r ejemplo/requirements.txt; fi
    
    - name: Test with pytest
      run: |
        PYTHONPATH=. pytest -v